CREATE TABLE IF NOT EXISTS M_CHARACTER(
	id BIGINT(10) AUTO_INCREMENT COMMENT'ID',
	name VARCHAR(50) NOT NULL COMMENT'名前',
	attrcd VARCHAR(10) NOT NULL COMMENT'属性コード',
	rank VARCHAR(1) NOT NULL COMMENT'集計ランク',
	imgfilenm VARCHAR(100) NOT NULL COMMENT'画像ファイルパス',
	cmttxt text NOT NULL COMMENT'コメントテキスト',
	delflg VARCHAR(1) NOT NULL DEFAULT 0 COMMENT'削除フラグ',
	createdate VARCHAR(50) COMMENT'作成日時',
	updatedate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT'更新日時',
	CONSTRAINT m_character_pk PRIMARY KEY(id)
)
ENGINE InnoDB
comment='デフォルトキャラクターマスタ';
