CREATE TABLE IF NOT EXISTS M_HANYO(
	attrcd VARCHAR(10) NOT NULL COMMENT'汎用属性コード',
	attrname VARCHAR(100) NOT NULL COMMENT'汎用属性名',
	cmt VARCHAR(100) NOT NULL COMMENT'説明',
	delflg VARCHAR(1) NOT NULL DEFAULT 0 COMMENT'削除フラグ',
	createdate VARCHAR(50) COMMENT'作成日時',
	updatedate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT'更新日時',
	CONSTRAINT m_hanyo_pk PRIMARY KEY(attrcd)
)
ENGINE InnoDB
comment='汎用属性マスタ';
