CREATE TABLE IF NOT EXISTS M_PHTEST_BASIC(
	id BIGINT(10) NOT NULL COMMENT'ID',
	content VARCHAR(100) NOT NULL COMMENT'質問内容',
	attrcd VARCHAR(10) NOT NULL COMMENT'属性コード',
	delflg VARCHAR(1) NOT NULL DEFAULT 0 COMMENT'削除フラグ',
	createdate VARCHAR(50) COMMENT'作成日時',
	updatedate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT'更新日時',
	CONSTRAINT m_phtest_basic_pk PRIMARY KEY(id)
)
ENGINE InnoDB
comment='基本心理テストマスタ';
