CREATE TABLE IF NOT EXISTS M_TOTALCOMMENT(
	id BIGINT(10) AUTO_INCREMENT COMMENT'ID',
	minval BIGINT(10) NOT NULL COMMENT'下限累計値',
	maxval BIGINT(10) NOT NULL COMMENT'上限累計値',
	cmttxt text NOT NULL COMMENT'コメントテキスト',
	delflg VARCHAR(1) NOT NULL DEFAULT 0 COMMENT'削除フラグ',
	createdate VARCHAR(50) COMMENT'作成日時',
	updatedate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT'更新日時',
	CONSTRAINT m_totalcomment_pk PRIMARY KEY(id)
)
ENGINE InnoDB
comment='累計コメントマスタ';
