CREATE TABLE IF NOT EXISTS M_USER(
	seq BIGINT(10) AUTO_INCREMENT COMMENT'順序',
	userid VARCHAR(50) NOT NULL COMMENT'表示名',
	userpswd VARCHAR(50) NOT NULL COMMENT'パスワード',
	email VARCHAR(100) NOT NULL COMMENT'メールアドレス',
	token VARCHAR(40) NOT NULL COMMENT'トークン',
	charaid BIGINT(10) NOT NULL COMMENT'キャラクターID',
	course VARCHAR(10) NOT NULL COMMENT'コース選択',
	limitdate VARCHAR(50) NOT NULL COMMENT'育成期限日時',
	delflg VARCHAR(1) NOT NULL DEFAULT 0 COMMENT'削除フラグ',
	createdate VARCHAR(50) COMMENT'作成日時',
	updatedate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT'更新日時',
	CONSTRAINT m_user_pk PRIMARY KEY(seq)
)
ENGINE InnoDB
comment='ユーザーマスタ';
