CREATE TABLE IF NOT EXISTS T_PHTEST_GROWTH_HISTORY(
	seq BIGINT(10) AUTO_INCREMENT COMMENT'順序',
	userid VARCHAR(100) NOT NULL COMMENT'ユーザID',
	phid BIGINT(10) NOT NULL COMMENT'質問ID',
	attrcd VARCHAR(10) NOT NULL COMMENT'属性コード',
	answer VARCHAR(1) NOT NULL COMMENT'回答',
	prifix VARCHAR(2) NOT NULL COMMENT'加減接頭辞',
	val BIGINT(10) NOT NULL COMMENT'加減値',
	createdate TIMESTAMP COMMENT'作成日時',
	CONSTRAINT t_phtest_growth_history_pk PRIMARY KEY(seq)
)
ENGINE InnoDB
comment='育成心理テスト履歴テーブル';
