CREATE TABLE IF NOT EXISTS T_SURVEY_HISTORY(
	seq BIGINT(10) AUTO_INCREMENT COMMENT'順序',
	id VARCHAR(40) NOT NULL COMMENT'ID',
	age VARCHAR(10) NOT NULL COMMENT'年代',
	gender VARCHAR(10) NOT NULL COMMENT'性別',
	createdate TIMESTAMP COMMENT'作成日時',
	CONSTRAINT t_survey_history_pk PRIMARY KEY(seq)
)
ENGINE InnoDB
comment='アンケート履歴テーブル';
